In [2]:
import torch
import signatory

In [10]:
path

tensor([[[0.7002, 0.5727],
         [0.5294, 0.3566],
         [0.4598, 0.6620],
         [0.4804, 0.4413],
         [0.9565, 0.6656],
         [0.0999, 0.5592],
         [0.7935, 0.8055],
         [0.2871, 0.5132]]])

In [23]:
path

tensor([[[0.0206, 0.6516],
         [0.4945, 0.5398],
         [0.5117, 0.6047],
         [0.8848, 0.7814],
         [0.3468, 0.4179],
         [0.9370, 0.5008],
         [0.6662, 0.5256],
         [0.8679, 0.1603]]])

In [35]:
signatory.all_words(2, 3)

[(0,),
 (1,),
 (0, 0),
 (0, 1),
 (1, 0),
 (1, 1),
 (0, 0, 0),
 (0, 0, 1),
 (0, 1, 0),
 (0, 1, 1),
 (1, 0, 0),
 (1, 0, 1),
 (1, 1, 0),
 (1, 1, 1)]

In [40]:
sig

tensor([[ 1.5965e-01, -4.1264e-01,  1.2744e-02, -1.2884e-04, -6.5749e-02,
          8.5136e-02,  6.7819e-04, -4.9400e-03,  9.8594e-03, -8.2087e-03,
         -1.0178e-02,  1.6471e-02,  5.3301e-03, -1.1710e-02]])

In [39]:
# Create a tensor of shape (2, 10, 5)
# Recall that the order of dimensions is (batch, stream, channel)
path = torch.rand(1, 8, 2)
# Take the signature to depth 3
depth = 3
sig = signatory.signature(path, depth)
# sig is of shape (2, 155)
sig

# append 0 at the beginning of each tuple in words
words = signatory.all_words(2, 3)
words = [(0,) + word for word in words]
for word in words:
    print(sig[word])

tensor(0.1596)
tensor(-0.4126)


IndexError: too many indices for tensor of dimension 2