In [10]:
import torch
import signatory
import numpy as np
import itertools
import trading_strategy
import utils

depth = 3
delta = 0.3
ts = trading_strategy.TradingStrategy(depth, delta)
batch_size = 2
d = 3 # number of stocks
N = 1 # size of info
Z_dim = N+d+1 # dimension of Z
T = 7 # number of time steps
batch_stock_data = torch.rand(batch_size, T, d) # X
batch_info_data = torch.rand(batch_size, T, N) # f
ts.fit(batch_stock_data, batch_info_data)

using shift f(0)=5
looking at words of length 0
words_k: []
level_k_signature.shape=torch.Size([10])
setting mu_i_sig[[]] to level_k_signature[[]]
looking at words of length 1
words_k: [[0]
 [1]
 [2]
 [3]
 [4]]
level_k_signature.shape=torch.Size([100])
setting mu_i_sig[[0]] to level_k_signature[[5]]
setting mu_i_sig[[1]] to level_k_signature[[6]]
setting mu_i_sig[[2]] to level_k_signature[[7]]
setting mu_i_sig[[3]] to level_k_signature[[8]]
setting mu_i_sig[[4]] to level_k_signature[[9]]
looking at words of length 2
words_k: [[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [3 0]
 [3 1]
 [3 2]
 [3 3]
 [3 4]
 [4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]]
level_k_signature.shape=torch.Size([1000])
setting mu_i_sig[[0 0]] to level_k_signature[[5 5]]
setting mu_i_sig[[0 1]] to level_k_signature[[5 6]]
setting mu_i_sig[[0 2]] to level_k_signature[[5 7]]
setting mu_i_sig[[0 3]] to level_k_signature[[5 8]]
setting mu_i_sig[[0 4]] to level_k_signatu

In [16]:
test=torch.rand(10)
print(test)

print(utils.get_level_k_words(2,5))

tensor([0.6234, 0.1861, 0.0505, 0.9354, 0.6797, 0.1564, 0.5272, 0.7561, 0.8303,
        0.3316])
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [3 0]
 [3 1]
 [3 2]
 [3 3]
 [3 4]
 [4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]]


In [19]:
test[np.array([1,2,3])]


tensor([0.1861, 0.0505, 0.9354])

In [ ]:
# i want to index a tensor with all the possible words with size between 